name: Story
description: Request a new feature or enhancement for Rezeptly
title: '[Story]: '
labels: ['feature']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature or enhancement!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the feature or enhancement
      placeholder: Tell us what you'd like to see!
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature important? What problem does it solve?
      placeholder: Explain the use case or benefit
    validations:
      required: true

  - type: textarea
    id: technical_hints
    attributes:
      label: Technical Hints
      description: Any suggestions or technical insights on how this feature could be implemented
      placeholder: Share any ideas on architecture, libraries, or approaches
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, links, or information about this feature
    validations:
      required: false
